-- 直播服务数据库
CREATE DATABASE IF NOT EXISTS heartmatch_live DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE heartmatch_live;

-- 直播间表
CREATE TABLE IF NOT EXISTS `live_room` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `title` VARCHAR(200) DEFAULT NULL,
    `cover_url` VARCHAR(500) DEFAULT NULL,
    `stream_url` VARCHAR(500) DEFAULT NULL,
    `viewer_count` INT DEFAULT 0,
    `like_count` INT DEFAULT 0,
    `status` TINYINT DEFAULT 0 COMMENT '0未开播 1直播中 2已结束',
    `started_at` DATETIME DEFAULT NULL,
    `ended_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 礼物表
CREATE TABLE IF NOT EXISTS `gift` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `icon` VARCHAR(200) DEFAULT NULL,
    `price` INT DEFAULT 0,
    `is_active` TINYINT DEFAULT 1,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 礼物记录表
CREATE TABLE IF NOT EXISTS `gift_record` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `room_id` BIGINT UNSIGNED NOT NULL,
    `sender_id` BIGINT UNSIGNED NOT NULL,
    `receiver_id` BIGINT UNSIGNED NOT NULL,
    `gift_id` BIGINT UNSIGNED NOT NULL,
    `count` INT DEFAULT 1,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 弹幕表
CREATE TABLE IF NOT EXISTS `danmu` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `room_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `content` VARCHAR(200) NOT NULL,
    `color` VARCHAR(20) DEFAULT '#FFFFFF',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY `idx_room` (`room_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
